version: 0.2
phases:
    install:
        commands:
            - mkdir -p ~/.ssh
            - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    pre_build:
        commands:
            - START_PATH=$(pwd)
            - BUILD_PATH=github.com/opolis/secret
            - pwd
            - mkdir -p $BUILD_PATH
            - cd $BUILD_PATH
            - cp -R $START_PATH/ .
            - dep ensure
    build:
        commands:
            - go build -o secret main.go
artifacts:
    files: secret
cache:
    paths:
        - 'vendor/**/*'
