version: 0.2
phases:
    install:
        commands:
            - mkdir -p ~/.ssh
            - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    pre_build:
        commands:
            - PACKAGE=github.com/opolis/secret
            - mkdir -p /go/src/$PACKAGE
            - cp -a $CODEBUILD_SRC_DIR/. /go/src/$PACKAGE
    build:
        commands:
            - cd /go/src/$PACKAGE && dep ensure
            - cd /go/src/$PACKAGE && go build -o $CODEBUILD_SRC_DIR/secret main.go
artifacts:
    files: secret
cache:
    paths:
        - '/go/src/github.com/opolis/secret/vendor/**/*'
