version: 0.2
env:
    variables:
        SRC_DIR: src/github.com/opolis/secret
phases:
    install:
        commands:
            - mkdir -p ~/.ssh
            - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    pre_build:
        commands:
            - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
            - echo GOPATH - $GOPATH
            - PACKAGE=github.com/opolis/secret
            - mkdir -p $GOPATH/src/$PACKAGE
            - cp -a $CODEBUILD_SRC_DIR/. $GOPATH/src/$PACKAGE
    build:
        commands:
            - cd $GOPATH/src/$PACKAGE && dep ensure
            - cd $GOPATH/src/$PACKAGE && go build -o $CODEBUILD_SRC_DIR/secret main.go
artifacts:
    files: secret
cache:
    paths:
        - 'vendor/**/*'
