version: 0.2
env:
    variables:
        SRC_DIR: src/github.com/opolis/secret
phases:
    install:
        commands:
            - mkdir -p ~/.ssh
            - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    pre_build:
        commands:
            - pwd
            - dep ensure
    build:
        commands:
            - go build -o secret main.go
artifacts:
    files: secret
cache:
    paths:
        - 'vendor/**/*'
